Server:
  HttpPort: :8080
Database:
  DBType: mysql
  Username: root
  Password: 12345678
  Host: 127.0.0.1:3306
  CharSet: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  DBName: catforest_test01
App:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  MaxSize: 100
  MaxAge: 1
  MaxBackups: 20
  Compress: True
  EncoderType: JSON
  EncoderConfigType: Development